Algoritmo "AprovadoOuNao"

Var
MEDIA, NOTA1, NOTA2, NOTA3: Real


Inicio
escreva("Qual sua nota em matematica?")
leia (NOTA1)
escreva("Qual sua nota em física?")
leia (NOTA2)
escreva("Qual sua nota em Português?")
leia (NOTA3)
MEDIA<-((NOTA1+NOTA2+NOTA3)/3)
escreva("Sua nota total é ", MEDIA2:1)
se(MEDIA >= 7.5) entao
escreval(" Você foi aprovado") senao
escreval(" Você foi reprovado")

fimse
Fimalgoritmo